development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      # uri: mongodb://user:password@mongodb.domain.com:27017/threadmill_development

      # Otherwise define the parameters separately.
      # This defines the name of the default database that Mongoid can connect to.
      # (required).
      database: threadmill_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
        - localhost:27018
      options:
        compressors: [zstd, zlib]
        retry_writes: true
        max_read_retries: 3
        read:
          mode: :primary_preferred
        max_pool_size: 100
        wait_queue_timeout: 5
        socket_timeout: 60
          #max_connecting: 10

  # Configure Mongoid specific options. (optional)
  options:

production:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      # uri: mongodb://user:password@mongodb.domain.com:27017/threadmill_development

      # Otherwise define the parameters separately.
      # This defines the name of the default database that Mongoid can connect to.
      # (required).
      database: threadmill_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
        - localhost:27018
      options:
        compressors: [zstd, zlib]
        retry_writes: true
        max_read_retries: 3
        read:
          mode: :primary_preferred
        max_pool_size: 100
        wait_queue_timeout: 5
        socket_timeout: 60
          #max_connecting: 10

  # Configure Mongoid specific options. (optional)
  options:

test:
  clients:
    default:
      database: threadmill_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
